export const PRODUCT_CATEGORIES = [
    { label: 'Tops' },
    { label: 'Bottoms' },
    { label: 'Dresses' },
    { label: 'Outerwear' },
    { label: 'Undergarments' },
    { label: 'Activewear' },
    { label: 'Swimwear' },
    { label: 'Sleepwear' },
    { label: 'Accessories' },
    { label: 'Footwear' },
];

export const MATERIAL_TYPES = [
    { label: 'Cotton' },
    { label: 'Polyester' },
    { label: 'Silk' },
    { label: 'Wool' },
    { label: 'Denim' },
    { label: 'Leather' },
    { label: 'Suede' },
    { label: 'Satin' },
    { label: 'Velvet' },
    { label: 'Linen' },
    { label: 'Rayon' },
    { label: 'Nylon' },
    { label: 'Spandex' },
    { label: 'Lycra' },
    { label: 'Cashmere' },
    { label: 'Chiffon' },
    { label: 'Flannel' },
    { label: 'Gabardine' },
    { label: 'Georgette' },
    { label: 'Jersey' },
    { label: 'Lace' },
    { label: 'Muslin' },
    { label: 'Organza' },
    { label: 'Poplin' },
    { label: 'Tweed' },
    { label: 'Twill' },
    { label: 'Voile' },
    { label: 'Faux Fur' },
    { label: 'Fleece' },
    { label: 'Neoprene' },
    { label: 'Vinyl' },
    { label: 'Hemp' },
    { label: 'Jute' },
    { label: 'Bamboo' },
    { label: 'Modal' },
    { label: 'Tencel' },
    { label: 'Seersucker' },
    { label: 'Brocade' },
    { label: 'Corduroy' },
    { label: 'Damask' },
    { label: 'Khaki' },
    { label: 'Pique' },
    { label: 'Plisse' },
    { label: 'Velour' },
    { label: 'Acrylic' },
    { label: 'Microfiber' },
    { label: 'Polypropylene' },
    { label: 'Gore-Tex' },
    { label: 'Tyvek' },
];

export const FABRIC_CONSTRUCTIONS = [
    { label: 'Woven' },
    { label: 'Knit' },
    { label: 'Non-Woven' },
    { label: 'Synthetic' },
    { label: 'Blended' }
];
